import type { SpmsRecord } from './types'

export const spmsRecords: SpmsRecord[] = [
  {
    id: 'spms-001',
    orderNumber: 'SPMS-2026-0001',
    customer: 'Telkom Indonesia',
    customerOrderNumber: 'TSEL-PO-88214',
    requestDate: '2026-05-02',
    area: 'Jakarta',
    dop: 'DOP JKT-01',
    siteName: 'JKT-CBD-113',
    categoryMaterial: 'Radio',
    typeMaterial: 'Microwave Link',
    description: 'Replacement radio unit for capacity recovery',
    partNumber: 'AVI-CTR-9200',
    qty: 2,
    supportOriginMaterial: 'Warehouse Jakarta',
    severity: 'Critical',
    site: 'On Site',
    statusSpms: 'Waiting Approval',
    statusReturn: 'Not Returned',
  },
  {
    id: 'spms-002',
    orderNumber: 'SPMS-2026-0002',
    customer: 'Indosat Ooredoo Hutchison',
    customerOrderNumber: 'IOH-MW-7298',
    requestDate: '2026-04-18',
    area: 'Surabaya',
    dop: 'DOP SBY-03',
    siteName: 'SBY-RUNGKUT-042',
    categoryMaterial: 'Antenna',
    typeMaterial: 'Parabolic Antenna',
    description: 'Antenna alignment kit for corrective maintenance',
    partNumber: 'ANT-060-HPX',
    qty: 1,
    supportOriginMaterial: 'Warehouse Surabaya',
    severity: 'Medium',
    site: 'Remote Site',
    statusSpms: 'Approved',
    statusReturn: 'Closed',
  },
  {
    id: 'spms-003',
    orderNumber: 'SPMS-2026-0003',
    customer: 'XL Axiata',
    customerOrderNumber: 'XL-REQ-54012',
    requestDate: '2026-05-12',
    area: 'Bandung',
    dop: 'DOP BDG-02',
    siteName: 'BDG-DAGO-087',
    categoryMaterial: 'Power',
    typeMaterial: 'Rectifier Module',
    description: 'Power rectifier module for BTS continuity',
    partNumber: 'PWR-RCT-48V',
    qty: 4,
    supportOriginMaterial: 'Regional Stock',
    severity: 'High',
    site: 'On Site',
    statusSpms: 'In Progress',
    statusReturn: 'Partial Return',
  },
  {
    id: 'spms-004',
    orderNumber: 'SPMS-2026-0004',
    customer: 'Smartfren',
    customerOrderNumber: 'SF-PO-30189',
    requestDate: '2026-05-15',
    area: 'Medan',
    dop: 'DOP MDN-01',
    siteName: 'MDN-POLONIA-018',
    categoryMaterial: 'Cable',
    typeMaterial: 'IF Cable',
    description: 'IF cable replacement for unstable link',
    partNumber: 'CBL-IF-30M',
    qty: 6,
    supportOriginMaterial: 'Vendor Direct',
    severity: 'High',
    site: 'Tower Site',
    statusSpms: 'Rejected',
    statusReturn: 'Returned',
  },
  {
    id: 'spms-005',
    orderNumber: 'SPMS-2026-0005',
    customer: 'Telkomsel',
    customerOrderNumber: 'TSEL-PO-88265',
    requestDate: '2026-05-20',
    area: 'Makassar',
    dop: 'DOP MKS-04',
    siteName: 'MKS-PANAKKUKANG-006',
    categoryMaterial: 'Outdoor Unit',
    typeMaterial: 'ODU',
    description: 'Outdoor unit spare for preventive replacement',
    partNumber: 'ODU-11G-PLUS',
    qty: 3,
    supportOriginMaterial: 'Warehouse Makassar',
    severity: 'Low',
    site: 'On Site',
    statusSpms: 'New',
    statusReturn: 'Not Returned',
  },
  {
    id: 'spms-006',
    orderNumber: 'SPMS-2026-0006',
    customer: 'Biznet',
    customerOrderNumber: 'BIZ-SP-11872',
    requestDate: '2026-05-05',
    area: 'Semarang',
    dop: 'DOP SMG-02',
    siteName: 'SMG-TEMBALANG-091',
    categoryMaterial: 'Indoor Unit',
    typeMaterial: 'IDU',
    description: 'Indoor unit swap for service restoration',
    partNumber: 'IDU-CTR-500',
    qty: 2,
    supportOriginMaterial: 'Warehouse Jakarta',
    severity: 'Critical',
    site: 'Core Site',
    statusSpms: 'Waiting Approval',
    statusReturn: 'Partial Return',
  },
  {
    id: 'spms-007',
    orderNumber: 'SPMS-2026-0007',
    customer: 'Icon Plus',
    customerOrderNumber: 'ICON-MAT-4432',
    requestDate: '2026-05-21',
    area: 'Bali',
    dop: 'DOP DPS-01',
    siteName: 'DPS-SANUR-024',
    categoryMaterial: 'Connector',
    typeMaterial: 'RF Connector',
    description: 'Connector kit for urgent field repair',
    partNumber: 'RF-CON-NM',
    qty: 18,
    supportOriginMaterial: 'Regional Stock',
    severity: 'Medium',
    site: 'On Site',
    statusSpms: 'In Progress',
    statusReturn: 'Not Returned',
  },
  {
    id: 'spms-008',
    orderNumber: 'SPMS-2026-0008',
    customer: 'Moratelindo',
    customerOrderNumber: 'MORA-PO-9081',
    requestDate: '2026-05-22',
    area: 'Balikpapan',
    dop: 'DOP BPN-05',
    siteName: 'BPN-SEPINGGAN-014',
    categoryMaterial: 'Mounting',
    typeMaterial: 'Pole Mount',
    description: 'Pole mounting kit for new hop activation',
    partNumber: 'MNT-POLE-2M',
    qty: 5,
    supportOriginMaterial: 'Vendor Direct',
    severity: 'Low',
    site: 'Tower Site',
    statusSpms: 'Approved',
    statusReturn: 'Closed',
  },
]
