import type { SpmsRecord } from './types'

export const spmsRecords: SpmsRecord[] = [
  {
    id: 'spms-001',
    orderNumber: 'AVIAT-2026-0001',
    customer: 'Telkom',
    customerOrderNumber: 'TELKOM-PO-9081',
    requestDate: '2026-05-22',
    area: 'Balikpapan',
    dop: 'DOP BPN-05',
    feId: 'Khusus Telkom',
    neId: 'Khusus Telkom',
    regional: 'KALIMANTAN',
    siteName: 'BPN-SEPINGGAN-014',
    categoryMaterial: 'Mounting',
    typeMaterial: 'Pole Mount',
    description: 'Pole mounting kit for new hop activation',
    partNumber: 'MNT-POLE-2M',
    qty: 5,
    supportOriginMaterial: '',
    supportDestinationMaterial: '',
    materials: [
      {
        categoryMaterial: 'Mounting',
        typeMaterial: 'Pole Mount',
        description: 'Pole mounting kit for new hop activation',
        partNumber: 'MNT-POLE-2M',
        qty: 1,
        supportOriginMaterial: '',
        supportDestinationMaterial: '',
      },
      {
        categoryMaterial: 'Mounting',
        typeMaterial: 'Pole Mount',
        description: 'Pole mounting kit for new hop activation',
        partNumber: 'MNT-POLE-2M',
        qty: 1,
        supportOriginMaterial: '',
        supportDestinationMaterial: '',
      },
      {
        categoryMaterial: 'Mounting',
        typeMaterial: 'Pole Mount',
        description: 'Pole mounting kit for new hop activation',
        partNumber: 'MNT-POLE-2M',
        qty: 1,
        supportOriginMaterial: '',
        supportDestinationMaterial: '',
      },
      {
        categoryMaterial: 'Mounting',
        typeMaterial: 'Pole Mount',
        description: 'Pole mounting kit for new hop activation',
        partNumber: 'MNT-POLE-2M',
        qty: 1,
        supportOriginMaterial: '',
        supportDestinationMaterial: '',
      },
      {
        categoryMaterial: 'Mounting',
        typeMaterial: 'Pole Mount',
        description: 'Pole mounting kit for new hop activation',
        partNumber: 'MNT-POLE-2M',
        qty: 1,
        supportOriginMaterial: '',
        supportDestinationMaterial: '',
      },
    ],
    severity: 'Low',
    site: 'Tower Site',
    statusSpms: 'New',
    statusReturn: 'New',
    customerRequestor: 'Andi Rahman',
    picKancabEmail: 'saepulloh@aviat.id',
    picKancabName: 'Saepulloh',
    picKancabPhone: '082177708337',
    requestorEmail: 'andirhman@gmail.com',
    requestorPhone: '08129892923',
    statusTransaction: 'OOW',
  },
]
