import type { SpmsRecord } from './types'

export const spmsRecords: SpmsRecord[] = [
  {
    id: 'spms-001',
    orderNumber: 'AVIAT-2026-235',
    customer: 'Telkom',
    customerOrderNumber: 'INC45031007',
    requestDate: '2026-01-15',
    area: 'SUMBAGSEL',
    dop: 'PALEMBANG',
    feId: 'PBM002',
    neId: 'SAT027',
    regional: 'TREG I',
    siteName: 'SAT027_SUNGAI ROTAN_PBM002_PRABUMULIH 3',
    categoryMaterial: 'iPaso',
    typeMaterial: 'PDH',
    description: 'TRP-7G-2E SB G Low',
    partNumber: 'NWA-084117',
    qty: 1,
    supportOriginMaterial: '',
    supportDestinationMaterial: '',
    materials: [
      {
        categoryMaterial: 'iPaso',
        typeMaterial: 'PDH',
        description: 'TRP-7G-2E SB G Low',
        partNumber: 'NWA-084117',
        qty: 1,
        supportOriginMaterial: '',
        supportDestinationMaterial: '',
      },
    ],
    severity: 'Critical',
    site: 'SAT027',
    statusSpms: 'New',
    statusReturn: 'New',
    customerRequestor: 'HD Mitratel',
    picKancabEmail: 'ahmad.saepulloh@aviat.id',
    picKancabName: 'Ahmad Saepulloh',
    picKancabPhone: '081200001001',
    pmArea: 'Arie Setya',
    requestorEmail: '',
    requestorPhone: '',
    slaHours: '04:00:00',
    statusTransaction: 'OOW',
  },
  {
    id: 'spms-002',
    orderNumber: 'AVIAT-2026-2302',
    customer: 'Telkomsel',
    customerOrderNumber: 'RQR000000299316',
    requestDate: '2026-05-14',
    area: 'SUMBAGSEL',
    dop: 'LUBUKLINGGAU',
    feId: '',
    neId: '',
    regional: 'SUMBAGSEL',
    siteName: 'NOMAN (LLG037)',
    categoryMaterial: 'iPaso',
    typeMaterial: 'PDH',
    description:
      'iPaso400 IDU (16E1+2FE+2GBE) w/ 1 Modems (1+0) 100Mbps MDP-400MB-1AA',
    partNumber: 'NWA-055268',
    qty: 1,
    supportOriginMaterial: '',
    supportDestinationMaterial: '',
    materials: [
      {
        categoryMaterial: 'iPaso',
        typeMaterial: 'PDH',
        description:
          'iPaso400 IDU (16E1+2FE+2GBE) w/ 1 Modems (1+0) 100Mbps MDP-400MB-1AA',
        partNumber: 'NWA-055268',
        qty: 1,
        supportOriginMaterial: '',
        supportDestinationMaterial: '',
      },
    ],
    severity: 'Critical',
    site: 'LLG037',
    statusSpms: 'New',
    statusReturn: 'New',
    customerRequestor: 'Adi Pratama',
    picKancabEmail: 'gairah.prabu@aviat.id',
    picKancabName: 'Gairah Prabu',
    picKancabPhone: '081200001002',
    pmArea: 'Arie Setya',
    requestorEmail: 'adi.pratama@telkominfra.com',
    requestorPhone: '085268498420',
    slaHours: '04:00:00',
    statusTransaction: 'OOW',
  },
  {
    id: 'spms-003',
    orderNumber: 'AVIAT-2025-4378',
    customer: 'IOH',
    customerOrderNumber: 'INC-20250814-00023147',
    requestDate: '2025-08-31',
    area: 'SS',
    dop: 'JAMBI',
    feId: '',
    neId: '',
    regional: 'SUMATERA',
    siteName: '06MAB0033_RANTAU_KELOYANG_TB /06MAB0033',
    categoryMaterial: 'Hybrid',
    typeMaterial: 'MW',
    description: 'Hybrid 7/8G',
    partNumber: 'NWA-033801-001',
    qty: 1,
    supportOriginMaterial: '',
    supportDestinationMaterial: '',
    materials: [
      {
        categoryMaterial: 'Hybrid',
        typeMaterial: 'MW',
        description: 'Hybrid 7/8G',
        partNumber: 'NWA-033801-001',
        qty: 1,
        supportOriginMaterial: '',
        supportDestinationMaterial: '',
      },
    ],
    severity: 'Medium',
    site: '06MAB0033',
    statusSpms: 'New',
    statusReturn: 'New',
    customerRequestor: 'Mayda Manurung',
    picKancabEmail: 'arief@aviat.id',
    picKancabName: 'Arief',
    picKancabPhone: '081200001010',
    pmArea: 'Arie Setya',
    requestorEmail: 'mayida.manurung@ccsindo.com',
    requestorPhone: '08152523888',
    slaHours: '24:00:00',
    statusTransaction: 'OOW',
  },
]
